version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_ADMIN= ${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD= ${KEYCLOAK_PASS}
    command: [ "start-dev" ]
